title: Kali Sura # your name (or website title) here
logo: "/images/my_pic.JPG?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Aspiring software engineer looking for enhanced real-world experience. Has experience with data-oriented programming, data structures, Java, Python, OOP, Software Testing and is eager to learn more through an internship
  <br><br>
  <a href="https://www.linkedin.com/in/kali-sura-a02a50287/">View My LinkedIn Profile</a> 
  
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
google_analytics: G-89YR903VR0 # your Google Analytics tracking ID here
